# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'MyWall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyWall
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
  pod 'RealmSwift'
  pod 'SwiftLint'
  pod 'Result'
  pod 'MBProgressHUD'
  pod 'SwiftGen'
  pod 'IQKeyboardManagerSwift', '~> 6.2.0'
  pod 'KeychainSwift', '~> 15.0'
end
